### ISSUE TITLE
Error building Forthon in Python 3.3.2

### ISSUE THREAD

**Issue by jmlarson1** [dpgrote/Forthon#1]
I am unable to build Forthon using Python 3.3.2. The relevant errors are:

`Can't parse build/lib/Forthon/version.py: ParseError: bad input: type=2, value='3634', context=('', (2, 16))`
and
`File "/home/jlarson/.local/lib/python3.3/site-packages/Forthon/version.py", line 2`
`gitversion = 'b'3634cc7''`
`^`
`SyntaxError: invalid syntax`

The complete output is below:

[jlarson@blogin2 software]$ git clone https://github.com/dpgrote/Forthon.git
Initialized empty Git repository in /fusion/gpfs/home/jlarson/software/Forthon/.git/
remote: Counting objects: 2505, done.
remote: Total 2505 (delta 0), reused 0 (delta 0), pack-reused 2505
Receiving objects: 100% (2505/2505), 445.63 KiB, done.
Resolving deltas: 100% (1719/1719), done.
[jlarson@blogin2 software]$ cd Forthon/
[jlarson@blogin2 Forthon]$ python setup.py install --user
running install
running build
running build_py
creating build
creating build/lib
creating build/lib/Forthon
copying Lib/ForthonTimer.py -> build/lib/Forthon
copying Lib/Forthon_builder.py -> build/lib/Forthon
copying Lib/Forthon_options.py -> build/lib/Forthon
copying Lib/_Forthon.py -> build/lib/Forthon
copying Lib/__init__.py -> build/lib/Forthon
copying Lib/cfinterface.py -> build/lib/Forthon
copying Lib/compilers.py -> build/lib/Forthon
copying Lib/fvars.py -> build/lib/Forthon
copying Lib/interfaceparser.py -> build/lib/Forthon
copying Lib/preprocess.py -> build/lib/Forthon
copying Lib/wrappergen_derivedtypes.py -> build/lib/Forthon
copying Lib/wrappergenerator.py -> build/lib/Forthon
copying Lib/version.py -> build/lib/Forthon
Skipping implicit fixer: buffer
Skipping implicit fixer: idioms
Skipping implicit fixer: set_literal
Skipping implicit fixer: ws_comma
Can't parse build/lib/Forthon/version.py: ParseError: bad input: type=2, value='3634', context=('', (2, 16))
running build_scripts
creating build/scripts-3.3
copying and adjusting Forthon3 -> build/scripts-3.3
changing mode of build/scripts-3.3/Forthon3 from 644 to 755
running install_lib
copying build/lib/Forthon/ForthonTimer.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/Forthon_builder.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/Forthon_options.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/_Forthon.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/__init__.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/cfinterface.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/compilers.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/fvars.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/interfaceparser.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/preprocess.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/wrappergen_derivedtypes.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/wrappergenerator.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying build/lib/Forthon/version.py -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/ForthonTimer.py to ForthonTimer.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/Forthon_builder.py to Forthon_builder.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/Forthon_options.py to Forthon_options.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/_Forthon.py to _Forthon.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/__init__.py to **init**.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/cfinterface.py to cfinterface.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/compilers.py to compilers.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/fvars.py to fvars.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/interfaceparser.py to interfaceparser.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/preprocess.py to preprocess.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/wrappergen_derivedtypes.py to wrappergen_derivedtypes.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/wrappergenerator.py to wrappergenerator.cpython-33.pyc
byte-compiling /home/jlarson/.local/lib/python3.3/site-packages/Forthon/version.py to version.cpython-33.pyc
  File "/home/jlarson/.local/lib/python3.3/site-packages/Forthon/version.py", line 2
    gitversion = 'b'3634cc7''
                       ^
SyntaxError: invalid syntax

running install_scripts
copying build/scripts-3.3/Forthon3 -> /home/jlarson/.local/bin
changing mode of /home/jlarson/.local/bin/Forthon3 to 755
running install_data
copying License.txt -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying Src/Forthon.h -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
copying Src/Forthon.c -> /home/jlarson/.local/lib/python3.3/site-packages/Forthon
running install_egg_info
Removing /home/jlarson/.local/lib/python3.3/site-packages/Forthon-0.8.15-py3.3.egg-info
Writing /home/jlarson/.local/lib/python3.3/site-packages/Forthon-0.8.15-py3.3.egg-info

**Comment by jmlarson1** [comment]
The issue seems to arise from the block of code starting at line 28 in `setup.py`. The current commithash taken from git is `b'3634cc7'`. Therefore, either the string should be parsed to remove the `b` and ticks, or when it is written to `Lib/version.py`, there shouldn't be any ticks around the `%s`.

**Comment by dpgrote** [comment]
Thanks for the notification. This is now fixed.
 Dave
