### ISSUE TITLE
PyPI version (Double `update`)

### ISSUE THREAD

**Issue by ax3l** [dpgrote/Forthon#13]
@dpgrote I think you did hit `update` accidentally _twice_ and published `0.8.`**21** instead of `0.8.20` on PyPI.
- 4ce4503d10cf827558e84db53fa92c91907e241f
- f0c23c3a0f2ce789d535db32c790bd29ebe28724

**Comment by dpgrote** [comment]
It wasn't an accident, but I did do update twice. The first time, I had problems in my local repo and the update gave a few minor errors. It was easier to just run update again after fixing things rather than try to redo the update. I hope that it hasn't caused problems.

**Comment by ax3l** [comment]
Oh I see, all right!
