### ISSUE TITLE
FORTHON_PKGNAME undeclared

### ISSUE THREAD

**Issue by jmlarson1** [dpgrote/Forthon#2]
I am trying to use Forthon to build warp. The callpyfunc routine depends on the variable FORTHON_PKGNAME (in the file Forthon.c) that is undeclared. Is warp expected to declare this? 

The comment on the commit `b08eb865c3eef5473497295bc05ffc7eb5d0bc5a` suggests that warp used to be referenced. But commit `bb6e73395a5d84ef34098cd1b343b78780720da4` says that this work around is a hack specific to the warp code. 

I would think that FORTHON_PKGNAME would be declared by Forthon, and not by the application using Forthon. 

Thank you very much for the help!

**Comment by dpgrote** [comment]
I'm not sure why you're getting an error. FORTHON_PKGNAME is a macro, and is defined in warp in the file pywarp90/setup.py. It is also defined by Forthon to be the name of the package. What version of Warp do you have?

**Comment by jmlarson1** [comment]
I have Warp_Release_4.2. In pywarp90/setup.py, there is no mention of FORTHON_PKGNAME.

**Comment by dpgrote** [comment]
Ok - that is a slightly older version. You'll need to do a git pull to get the updates. Warp changes too rapidly to keep the most recent version on the downloads page. This is described in the Installation page in the wiki.

**Comment by jmlarson1** [comment]
I must not have been up to date. But I get a new error below. Tell me if I should post this elsewhere

[jlarson@blogin2 pywarp90]$ Forthon --version
0.8.15
[jlarson@blogin2 pywarp90]$ Forthon3 --version
0.8.15
[jlarson@blogin2 pywarp90]$ gfortran --version
GNU Fortran (GCC) 4.4.7 20120313 (Red Hat 4.4.7-11)
[jlarson@blogin2 simulation_software]$ cd warp/
[jlarson@blogin2 warp]$ git pull
Already up-to-date.
[jlarson@blogin2 warp]$ cd pywarp90/
[jlarson@blogin2 pywarp90]$ cat Makefile.local 
INSTALLOPTIONS = --user
[jlarson@blogin2 pywarp90]$ make -f Makefile.Forthon install
Forthon -a     top top_lattice.F top_fsl.F dtop.F util.F --build-base build --build-platlib build/tempsofiles
Building package top
  F90Fixed top.F
  Preprocess Forthon.h
  Preprocess Forthon.c
  F90Fixed top_lattice.F
  F90Fixed top_fsl.F
  F90Fixed dtop.F
  F90Fixed util.F
  Setup top
In file included from build/temp.linux-x86_64-3.3/toppymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     env --build-base build --build-platlib build/tempsofiles
Building package env
  Forthon env.v
  F90Free env_p.F90
  F90Fixed env.F
  Setup env
In file included from build/temp.linux-x86_64-3.3/envpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     --macros top.v w3d dw3d.F w3d_injection.F w3d_interp.F w3d_collisions.F w3d_load.F w3d_utilities.F --build-base build --build-platlib build/tempsofiles
Building package w3d
  Forthon w3d.v
  F90Free w3d_p.F90
  F90Fixed w3d.F
  F90Fixed dw3d.F
  F90Fixed w3d_injection.F
  F90Fixed w3d_interp.F
  F90Fixed w3d_collisions.F
  F90Fixed w3d_load.F
  F90Fixed w3d_utilities.F
  Setup w3d
In file included from build/temp.linux-x86_64-3.3/w3dpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     --macros top.v f3d f3d_mgrid.F f3d_ImplicitES.F f3d_mgrid_be.F f3d_bfield.F f3d_conductors.F fft.F --build-base build --build-platlib build/tempsofiles
Building package f3d
  Forthon f3d.v
  F90Free f3d_p.F90
  F90Fixed f3d.F
  F90Fixed f3d_mgrid.F
  F90Fixed f3d_ImplicitES.F
  F90Fixed f3d_mgrid_be.F
  F90Fixed f3d_bfield.F
  F90Fixed f3d_conductors.F
  F90Fixed fft.F
  Setup f3d
In file included from build/temp.linux-x86_64-3.3/f3dpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     wxy --build-base build --build-platlib build/tempsofiles
Building package wxy
  Forthon wxy.v
  F90Free wxy_p.F90
  F90Fixed wxy.F
  Setup wxy
In file included from build/temp.linux-x86_64-3.3/wxypymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     fxy fxy_mgrid.F --build-base build --build-platlib build/tempsofiles
Building package fxy
  Forthon fxy.v
  F90Free fxy_p.F90
  F90Fixed fxy.F
  F90Fixed fxy_mgrid.F
  Setup fxy
In file included from build/temp.linux-x86_64-3.3/fxypymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     --macros top.v wrz dwrz.F --build-base build --build-platlib build/tempsofiles
Building package wrz
  Forthon wrz.v
  F90Free wrz_p.F90
  F90Fixed wrz.F
  F90Fixed dwrz.F
  Setup wrz
In file included from build/temp.linux-x86_64-3.3/wrzpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     frz frz_mgrid.F90 frz_mgrid_be.F frz_ImplicitES.F --build-base build --build-platlib build/tempsofiles
Building package frz
  Forthon frz.v
  F90Free frz_p.F90
  F90Fixed frz.F
  F90Free frz_mgrid.F90
  F90Fixed frz_mgrid_be.F
  F90Fixed frz_ImplicitES.F
  Setup frz
In file included from build/temp.linux-x86_64-3.3/frzpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     her --build-base build --build-platlib build/tempsofiles
Building package her
  Forthon her.v
  F90Free her_p.F90
  F90Fixed her.F
  Setup her
In file included from build/temp.linux-x86_64-3.3/herpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     cir --build-base build --build-platlib build/tempsofiles
Building package cir
  Forthon cir.v
  F90Free cir_p.F90
  F90Fixed cir.F
  Setup cir
In file included from build/temp.linux-x86_64-3.3/cirpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     cho --build-base build --build-platlib build/tempsofiles
Building package cho
  Forthon cho.v
  F90Free cho_p.F90
  F90Fixed cho.F
  Setup cho
In file included from build/temp.linux-x86_64-3.3/chopymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     em2d em2d_apml.F90 em2d_apml_cummer.F90 em2d_maxwell.F90 --build-base build --build-platlib build/tempsofiles
Building package em2d
  Forthon em2d.v
  F90Free em2d_p.F90
  F90Free em2d.F90
  F90Free em2d_apml.F90
  F90Free em2d_apml_cummer.F90
  F90Free em2d_maxwell.F90
  Setup em2d
In file included from build/temp.linux-x86_64-3.3/em2dpymodule.c:1:
build/temp.linux-x86_64-3.3/Forthon.h:58: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:59: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:72: warning: function declaration isn’t a prototype
build/temp.linux-x86_64-3.3/Forthon.h:73: warning: function declaration isn’t a prototype
Forthon -a     em3d em3d_maxwell.F90 --build-base build --build-platlib build/tempsofiles
Building package em3d
  Forthon em3d.v
  F90Free em3d_p.F90
  F90Free em3d.F90
../../em3d.F90(816): error #6404: This name does not have a type, and must have an explicit type.   [COMPLEX]
  im = complex(0.,1.)
-------^
../../em3d.F90(3095): error #6404: This name does not have a type, and must have an explicit type.   [COMPLEX]
        xy0 = complex(c,s)
--------------^
../../em3d.F90(4516): error #6404: This name does not have a type, and must have an explicit type.   [COMPLEX]
          xy0 = complex(costheta,-sintheta)
----------------^
compilation aborted for ../../em3d.F90 (code 1)
make[1]: **\* [em3d.o] Error 1
make: **\* [em3dpy.so] Error 2
