### ISSUE TITLE
Fails to build with Debian/Ubuntu mpich>=3.3-2 due to compiler alias

### ISSUE THREAD

**Issue by PhilMiller** [dpgrote/Forthon#28]
When trying to build MPI code using Forthon with MPICH and gfortran on recent Debian or Ubuntu (specifically, 20.04 Focal Fossa), I find that Forthon fails with the error `Fortran compiler not found`.

This seems to be because the `mpifort` provided in the Debian `mpich` package executes the Fortran compiler via the `f95` alias rather than an explicit `gfortran`. I'm guessing this was done because there's another Debian package, `flang-7`, that also provides an implementation of that alias, via the Debian 'alternatives' system which maintains symlinks `/usr/bin/f95 -> /etc/alternatives/f95 -> /usr/bin/{gfortran,flang}`

Thus, in `compilers.py`, either the compiler is not found (if `--fcomp` is unspecified), or the assertion that the command line given by `mpifort -show` begins with the specified name fails. 

I'm not sure of the best way to resolve this. Forthon could trust the user's specification of compiler type, at the expense of the consistency checking it does now. It could go down the rabbit hole of recursively resolving symlinks (which would fail  on further wrappers) or running the command specified to get version output and interpreting that.

**Comment by dpgrote** [comment]
Can you try using the `--fcompexec` option, for example `--fcompexec f95`? This allows specifying the name of the executable if it is different than the standard name.

**Comment by PhilMiller** [comment]
I'm passing `--fcompexec mpifort`, since I need to use the MPI wrapper to get the necessary compiler and linker flags.

Typical compiler command line absent attempts to adapt to this is 

> `Forthon3 -a --pkgsuffix parallel  --pkgbase warp --build-base build3parallel --install   --fcompexec mpifort --farg "-g -O3 -march=native"  --farg "-DMPIPARALLEL" top top_lattice.F top_fsl.F dtop.F util.F topslave.F --user`

**Comment by dpgrote** [comment]
I've added a new command line argument that will solve this issue. Update your Forthon and add this `--mpifort_compiler f95`. I tested it and it works.

**Comment by PhilMiller** [comment]
Ok, the Forthon build steps seems to be working now. My makefile assembles this list of arguments, to be compatible with both the `mpich` package that uses the `f95` alias, and the `openmpi` package that uses `gfortran` directly:

> `FCOMPEXEC := --fcompexec=mpifort --fcomp=gfortran --mpifort_compiler=$(shell mpifort -show | cut -d' ' -f1)`

The subsequent WARP install step still fails, because its `setup.py` doesn't recognize the new argument, and without it, the install step's instantiation of `FCompiler` hits the same failure case as the compilation step

**Comment by dpgrote** [comment]
This is a Warp issue - I'll post a fix there.

I'm taking a poll - which version of Python do you use?

**Comment by PhilMiller** [comment]
Thanks.

We've got production runs going on 3.7. We just made changes to our code to support 3.8, and will likely be migrating to that on Ubuntu 20.04 soon.

**Comment by PhilMiller** [comment]
Ok, with the corresponding WARP fix in hand, this all works. Thank you for the help!

**Comment by PhilMiller** [comment]
Oops, I may have spoken too soon. It looks like this breaks serial builds of WARP that *don't* pass `--mpifort_compiler`

**Comment by PhilMiller** [comment]
There's a missing `mpifort_compiler = None` in `setup.py`

**Comment by dpgrote** [comment]
Oops, yes. This is now fixed.

**Comment by PhilMiller** [comment]
All seems to be well. Thanks
