### ISSUE TITLE
broken link in About section

### ISSUE THREAD

**Issue by Beliavsky** [dpgrote/Forthon#31]
The link in the About section is broken.

**Comment by dpgrote** [comment]
Thanks for the notice. The link is removed. I've also updated the Python versions since it was way out of date.

**Comment by Beliavsky** [comment]
I still see the broken link in the About section.

**Comment by dpgrote** [comment]
Now, that link is removed. There is no other website for Forthon anymore. That page didn't have much additional information anyway.
